# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('adress', models.TextField(max_length=200)),
                ('quality', models.TextField(max_length=200)),
                ('signal', models.TextField(max_length=200)),
                ('channel', models.TextField(max_length=200)),
                ('encryption', models.TextField(max_length=200)),
            ],
        ),
    ]
