# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omf', '0003_signal_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='time',
        ),
    ]
